AttendanceMVC/Controllers/OthersController.cs
using AttendanceMVC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Web.UI;
using System.Globalization;
using System.Data.OleDb;
using System.IO;

namespace AttendanceMVC.Controllers
{
    public class OthersController : Controller
    {
        static string Ccode = "";
        static string Lcode = "";
        static string SessionCcode = "";
        static string SessionLcode = "";
        static string SessionUserName;
        static string SessionUserID;

        string SSQL = "";
        DateTime date1;
        DateTime date2;
        DateTime Date2 = new DateTime();

        string PartyName;
        DateTime frmDate;
        DateTime toDate;
        string Machine_ID_Encrypt;
        static bool isUK = false;
        string mIpAddress_IN;
        string mIpAddress_OUT;

        static string EmpNo = "", ExisistingCode = "", MachineNo = "", Days = "", Months = "", FinancialYear = "", PFSS = "";
        static string TotalDays = "", NFh = "", weekoff = "", OTHoursNew = "", Fixed_Work_Days = "", NFH_Work_Days_Statutory = "", WH_Work_Present = "";
        static string BasicSalary = "", Allowance1amt = "", Allowance2amt = "", Deduction1amt = "", Deduction2amt = "", ConvenyAmt = "", SplAmt = "";
        static string ExistingCode = "", MachineID = "", EligibleCateen = "", EligibleIncentive = "", EligibleSnacks = "", Eligible_PF = "", Eligible_ESI = "";
        static string PF_per = "", ESI_per = "", StaffSalary = "", EmployeerPFone = "", EmployeerPFTwo = "", EmployeerESI = "";
        string basic1 = "0.00";
        string HRA1 = "0.00";
        string SplAllow1 = "0.00";
        static string basic = "0";
        static string hours = "0";
        static string hours1 = "0";
        static string Advance = "0";
        static string pfAmt = "0";
        static string ESI = "0";
        static string stamp = "0";
        static string Union = "0";
        static string TotalEarnings = "0";
        static string TotalDeductions = "0";
        static string NetPay = "0";
        static string Words = "";
        static string PFS = "0.00";
        static string ExistNo = "";
        static string PF_salary;
        static string Employer_PF = "0.00";
        static string Employer_ESI = "0.00";
        static string ded3 = "0";
        static string ded4 = "0";
        static string ded5 = "0";
        static string All3 = "0";
        static string All4 = "0";
        static string All5 = "0";
        static string CanteenDays = "0";
        static string HRA_Str = "0";
        static string Spl_Allow_Str = "0";

        static string All1 = "0";
        static string All2 = "0";
        static string Ded1 = "0";
        static string ded2 = "0";
        static string DayIncentive = "0";




        // GET: Others
        public ActionResult AttendanceUpload()
        {
            if (Session["SessionCcode"] != null)
            {
                SessionCcode = Session["SessionCcode"].ToString();
                SessionLcode = Session["SessionLcode"].ToString();
                SessionUserName = Session["Usernmdisplay"].ToString();
                SessionUserID = Session["UserId"].ToString();

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult SalaryUpload()
        {
            if (Session["SessionCcode"] != null)
            {
                SessionCcode = Session["SessionCcode"].ToString();
                SessionLcode = Session["SessionLcode"].ToString();
                SessionUserName = Session["Usernmdisplay"].ToString();
                SessionUserID = Session["UserId"].ToString();

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult AttendanceUpload(string FromDate, string ToDate, string WagesType, string FinYear, string Months, HttpPostedFileBase file)
        {
            bool ErrFlag = false;
            string message = "";
            DataTable SHift = new DataTable();
            string Year = "";
            string Month = "";
            string SSQL = "";
            DataTable DT = new DataTable();
            DataTable DT_Check = new DataTable();

            List<ManualAttend> empList = new List<ManualAttend>();

            if (FromDate == "")
            {
                ErrFlag = true;
                Response.Write("<script>alert('Enter the FromDate')</script>");

            }
            else if (ToDate == "")
            {
                ErrFlag = true;
                Response.Write("<script>alert('Enter the ToDate')</script>");

            }
            else if (WagesType == "0")
            {
                ErrFlag = true;
                Response.Write("<script>alert('Select the WagesType')</script>");

            }
            else if (FinYear == "0")
            {
                ErrFlag = true;
                Response.Write("<script>alert('Select the Financial Year')</script>");

            }
            else if (Months == "0")
            {
                ErrFlag = true;
                Response.Write("<script>alert('Select the Month')</script>");

            }
            if (!ErrFlag)
            {
                date1 = Convert.ToDateTime(FromDate);
                Date2 = Convert.ToDateTime(ToDate);
                int daycount = (int)(((Date2 - date1).TotalDays) + 1);
                //string Mn = Convert.ToDateTime(FromDate).ToString("MMMM");
                //string yy = Convert.ToDateTime(FromDate).Year.ToString();

                string Mn = Months.ToString();
                string yy = FinYear.ToString();

                DataTable dt = new DataTable();
                DataTable DT_Wages = new DataTable();
                string Wages = "0";
                DataSet ds = new DataSet();


                //return Content("<script language='javascript' type='text/javascript'>alert     ('Requested Successfully ');</script>");
                string excelConnectionString = "";

                if (Request.Files["file"].ContentLength > 0)
                {
                    string fileExtension =
                                        System.IO.Path.GetExtension(Request.Files["file"].FileName);
                    if (fileExtension == ".xls" || fileExtension == ".xlsx")
                    {
                        string fileLocation = Path.GetFileName(Request.Files["file"].FileName);
                        string filename = fileLocation;
                        string targetpath = Server.MapPath("~/Upload/");
                        file.SaveAs(targetpath + filename);
                        string pathToExcelFile = targetpath + filename;
                        var connectionString = "";
                        if (fileExtension == ".xls")
                        {
                            //  connectionString = string.Format("Provider=Microsoft.Jet.OLEDB.4.0; data source={0}; Extended Properties=Excel 8.0;", pathToExcelFile);
                            connectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + pathToExcelFile + ";Extended Properties=Excel 12.0;";
                        }
                        //connection String for xlsx file format.
                        else if (fileExtension == ".xlsx")
                        {
                            connectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + pathToExcelFile + ";Extended Properties=Excel 12.0;";
                        }
                        //Create Connection to Excel work book and add oledb namespace
                        OleDbConnection excelConnection = new OleDbConnection(connectionString);
                        excelConnection.Open();
                        //DataTable dt = new DataTable();

                        OleDbCommand command = new OleDbCommand("Select * FROM [Sheet1$];", excelConnection);
                        excelConnection.Close();

                        using (OleDbCommand cmd = excelConnection.CreateCommand())
                        {
                            command.CommandText = "Select * FROM [Sheet1$];";
                            excelConnection.Open();
                        }
                        using (OleDbDataReader dr = command.ExecuteReader())
                        {

                            if (dr.HasRows)
                            {

                            }

                        }
                        OleDbDataAdapter objDataAdapter = new OleDbDataAdapter();
                        objDataAdapter.SelectCommand = command;


                        objDataAdapter.Fill(ds);

                        dt = ds.Tables[0];

                        if (WagesType == "3")
                        {
                            for (int i = 0; i < dt.Rows.Count; i++)
                            {

                                string Department = dt.Rows[i][4].ToString();
                                string DeptCode = "0";
                                DataTable DT_Dept = new DataTable();
                                SSQL = "Select *from Department_Mst where CompCode='" + SessionCcode + "' And LocCode='" + SessionLcode + "'";
                                SSQL = SSQL + " And DeptName='" + Department.Trim() + "'";
                                DT_Dept = ManualAttend.GetDetails(SSQL);

                                if (DT_Dept.Rows.Count != 0)
                                {
                                    DeptCode = DT_Dept.Rows[0]["DeptCode"].ToString();
                                }

                                string MachineID = dt.Rows[i][1].ToString();

AttendanceMVC/Views/Others/AttendanceDownload.cshtml
@{
    ViewBag.Title = "AttendanceDownload";
    Layout = "~/Views/Shared/PayrollMaster.cshtml";
}

<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;">Attendance Download</a></li>

    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header"><small>Attendance</small></h1>
    <!-- end page-header -->
    <!--Form Page-->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        @*<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>*@
                    </div>
                    <h4 class="panel-title">Attendance Download</h4>
                </div>
                <div class="panel-body panel-form">
                    <div class="form-horizontal form-bordered" data-parsley-validate="true">
                        <div class="form-group">

                            <div class="row">
                                <div class="col-md-4">
                                    <label>Employee Type * :</label>
                                    <select id="ddlAttendEmpType" class="form-control select2">
                                        <option value="0">--Select Employee Type--</option>
                                    </select>
                                    <span id="AttendEmpTypeerror" style="color:red"></span>
                                </div>
                                <div class="col-md-2">
                                    <br />
                                    <button type="button" class="btn btn-primary" id="btnAttendDownload">Download</button>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/Salary/SalaryAndAttendance.js"></script>

AttendanceMVC/Views/Others/AttendanceUpload.cshtml
@{
    ViewBag.Title = "AttendanceUpload";
    Layout = "~/Views/Shared/PayrollMaster.cshtml";
}

@using (Html.BeginForm("AttendanceUpload", "Others", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

          <!-- begin #content -->
    <div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li><a href="javascript:;">Salary</a></li>
            <li><a href="javascript:;">Attendance Upload</a></li>

        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header"><small>Attendance Upload</small></h1>
        <!-- end page-header -->
        <!--Form Page-->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                            @*<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>*@
                        </div>
                        <h4 class="panel-title">Attendance Upload</h4>
                    </div>
                    <div class="panel-body panel-form">
                        <div class="form-horizontal form-bordered" data-parsley-validate="true">
                            <div class="form-group">

                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Employee Type * :</label>
                                        <select id="ddlEmpType" class="form-control select2" name="WagesType" data-parsley-required="true" required>
                                            <option value="0">--Select Employee Type--</option>
                                        </select>

                                    </div>
                                    <div class="col-md-4">
                                        <label>From Date  * :</label>
                                        <input class="form-control datepicker" type="text" id="txtFromDate" name="FromDate" data-parsley-required="true" />
                                        <span id="FromDateerror" style="color:red"></span>
                                    </div>
                                    <div class="col-md-4">
                                        <label>To Date * :</label>
                                        <input class="form-control datepicker" type="text" id="txtToDate" name="ToDate" />
                                        <span id="txtToDateerror" style="color:red"></span>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-md-4">
                                        <label>Financial Year</label>
                                        <select id="ddlFin" class="form-control select2" name="FinYear">
                                            <option value="0">-Select-</option>
                                        </select>
                                    </div>

                                    <div class="col-md-4">
                                        <label>Month</label>
                                        <select id="ddlMonth" class="form-control select2" name="Months">
                                            <option value="0">-Select-</option>
                                            <option>January</option>
                                            <option>February</option>
                                            <option>March</option>
                                            <option>April</option>
                                            <option>May</option>
                                            <option>June</option>
                                            <option>July</option>
                                            <option>August</option>
                                            <option>September</option>
                                            <option>October</option>
                                            <option>November</option>
                                            <option>December</option>
                                        </select>

                                    </div>

                                    <div class="col-md-3">
                                        <br />
                                        <input type="file" id="fileUpload" Name="file" class="btn btn-default btn-rounded">
                                        <span class="" id="fileUploaderror" style="color:red;"></span>
                                    </div>

                                </div>

                                <div class="row">
                                    <label class="control-label col-md-5 col-sm-5"></label>
                                    <div class="col-md-3 col-sm-3">
                                        <button type="submit" class="btn btn-success" id="btnAttendMove">Attendance Upload</button>
                                    </div>
                                    <div class="col-md-3 col-sm-3">

                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


        <script src="~/Scripts/jquery.min.js"></script>
        <script src="~/Scripts/Salary/Others.js"></script>
}

AttendanceMVC/Views/Others/SalaryDownload.cshtml
@{
    ViewBag.Title = "SalaryDownload";
    Layout = "~/Views/Shared/PayrollMaster.cshtml";
}

<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;">Salary Download</a></li>

    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header"><small>Salary</small></h1>
    <!-- end page-header -->
    <!--Form Page-->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        @*<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>*@
                    </div>
                    <h4 class="panel-title">Salary Download</h4>
                </div>
                <div class="panel-body panel-form">
                    <div class="form-horizontal form-bordered" data-parsley-validate="true">
                        <div class="form-group">

                            <div class="row">
                                <div class="col-md-4">
                                    <label>Employee Type * :</label>
                                    <select id="ddlSalaryEmpType" class="form-control select2">
                                        <option value="0">--Select Employee Type--</option>
                                    </select>
                                    <span id="SalaryEmpTypeerror" style="color:red"></span>
                                </div>
                                <div class="col-md-2">

                                    <br />
                                    <button type="button" class="btn btn-primary" id="btnSalaryDownload">Download</button>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/Salary/SalaryAndAttendance.js"></script>

AttendanceMVC/Views/Others/SalaryUpload.cshtml
@{
    ViewBag.Title = "SalaryUpload";
    Layout = "~/Views/Shared/PayrollMaster.cshtml";
}

@using (Html.BeginForm("SalaryUpload", "Others", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <!-- begin #content -->
    <div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li><a href="javascript:;">Salary</a></li>
            <li><a href="javascript:;">Salary Upload</a></li>

        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header"><small>Salary Upload</small></h1>
        <!-- end page-header -->
        <!--Form Page-->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                            @*<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>*@
                        </div>
                        <h4 class="panel-title">Salary Upload</h4>
                    </div>
                    <div class="panel-body panel-form">
                        <div class="form-horizontal form-bordered" data-parsley-validate="true">
                            <div class="form-group">

                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Employee Type * :</label>
                                        <select id="ddlEmpType" class="form-control select2" name="WagesType">
                                            <option value="0">--Select Employee Type--</option>
                                        </select>

                                    </div>
                                    <div class="col-md-4">
                                        <label>From Date  * :</label>
                                        <input class="form-control datepicker" type="text" id="txtFromDate" name="FromDate" placeholder="Required" data-parsley-required="true" />
                                        <span id="FromDateerror" style="color:red"></span>
                                    </div>
                                    <div class="col-md-4">
                                        <label>To Date * :</label>
                                        <input class="form-control datepicker" type="text" id="txtToDate" name="ToDate" placeholder="Required" data-parsley-required="true" />
                                        <span id="txtToDateerror" style="color:red"></span>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Financial Year</label>
                                        <select id="ddlFin" class="form-control select2" name="FinYear">
                                            <option value="0">-Select-</option>
                                        </select>

                                    </div>

                                    <div class="col-md-4">
                                        <label>Month</label>
                                        <select id="ddlMonth" class="form-control select2" name="Months">
                                            <option value="0">-Select-</option>
                                            <option>January</option>
                                            <option>February</option>
                                            <option>March</option>
                                            <option>April</option>
                                            <option>May</option>
                                            <option>June</option>
                                            <option>July</option>
                                            <option>August</option>
                                            <option>September</option>
                                            <option>October</option>
                                            <option>November</option>
                                            <option>December</option>
                                        </select>

                                    </div>

                                    <div class="col-md-3">
                                        <br />
                                        <input type="file" id="fileUpload" Name="file" class="btn btn-default btn-rounded">
                                        <span class="" id="fileUploaderror" style="color:red;"></span>
                                    </div>

                                </div>



                                <div class="row">
                                    <label class="control-label col-md-5 col-sm-5"></label>
                                    <div class="col-md-3 col-sm-3">
                                        <button type="submit" class="btn btn-success" id="btnAttendMove">Salary Upload</button>
                                    </div>
                                    <div class="col-md-3 col-sm-3">

                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/Salary/Others.js"></script>
}